src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $nom = null;

    #[ORM\Column(length: 4)]
    private ?string $annee = null;

    #[ORM\OneToMany(mappedBy: 'promotion', targetEntity: Etudiant::class)]
    private Collection $etudiants;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAnnee(): ?string
    {
        return $this->annee;
    }

    public function setAnnee(string $annee): static
    {
        $this->annee = $annee;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): static
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants->add($etudiant);
            $etudiant->setPromotion($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): static
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getPromotion() === $this) {
                $etudiant->setPromotion(null);
            }
        }

        return $this;
    }

    public function getNbEtudiant(): int{
        return count($this->etudiants);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Repository\PromotionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PromotionController extends AbstractController
{
    #[Route('/promotions', name: 'app_promotions')]
    public function list(PromotionRepository $promotionRepository): Response
    {
        $promotions = $promotionRepository->findAll();
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotions
        ]);
    }

    #[Route('/promotions/{id}', name: 'app_promotions_info', requirements: ['id'=>'\d+'] )]
    public function info(PromotionRepository $promotionRepository, int $id): Response
    {
        $promotion = $promotionRepository->find($id);
        return $this->render('promotion/infoPromotion.html.twig', [
            'promotion' => $promotion
        ]);
    }
}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotions{% endblock %}

{% block body %}
<div class="contenu">
    <h1>Promotions</h1>
    <ul>
        {% for promotion in promotions %}
            <li><a href="{{ path('app_promotions_info', {"id" : promotion.id}) }}">{{ promotion.nom }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/promotion/infoPromotion.html.twig
{% extends 'base.html.twig' %}

{%  block title %} {{ promotion.nom|capitalize }} {% endblock %}

{% block body %}
    <div class="contenu">
        <h1>INFORMATIONS D'UNE PROMOTION</h1>
        <p>Nom : {{ promotion.nom }}</p>
        <p>Année : {{ promotion.annee }}</p>
        <p>Nombre d'étudiants : {{ promotion.nbEtudiant }}</p>

        <h3>Liste des étudiants</h3>
        <ul>
            {% for etudiant in promotion.etudiants|sort((a, b) => a.nom > b.nom) %}
                <li><a href="{{ path('app_etudiant_info', {"id_etudiant" : etudiant.id}) }}">{{ etudiant.prenom }} {{ etudiant.nom }}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}